In [11]:
# Importa o pandas para trabalhar com tabelas de dados
import pandas as pd

# Importa o yfinance para buscar dados financeiros
import yfinance as yf

In [12]:
# Solicita o histórico da ação XP a partir de 1º de dezembro de 2019
# Guarda os dados na variável xp, sem salvar um arquivo no computador
xp = yf.download("XP", start="2019-12-01")

# Mostra as cinco primeiras linhas para conferir o resultado
xp.head()

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open    Volume
Ticker             XP         XP         XP         XP        XP
Date
2019-12-11  30.322840  30.798010  28.246173  28.818138  34635800
2019-12-12  30.481230  32.962669  29.416499  29.988464   8121000
2019-12-13  33.182652  33.719417  30.006057  30.534024   5115700
2019-12-16  31.501959  33.869008  30.578019  33.279444   3946300
2019-12-17  30.182049  31.554761  29.358421  31.554761   2336500

In [13]:
# Mantém apenas o primeiro nível do cabeçalho, com os nomes dos campos
xp.columns = xp.columns.get_level_values(0)

# Mostra as cinco primeiras linhas para conferir a mudança
xp.head()

Price           Close       High        Low       Open    Volume
Date
2019-12-11  30.322840  30.798010  28.246173  28.818138  34635800
2019-12-12  30.481230  32.962669  29.416499  29.988464   8121000
2019-12-13  33.182652  33.719417  30.006057  30.534024   5115700
2019-12-16  31.501959  33.869008  30.578019  33.279444   3946300
2019-12-17  30.182049  31.554761  29.358421  31.554761   2336500

In [14]:
# Mostra a quantidade de linhas e colunas, nessa ordem
xp.shape

(1729, 5)

In [15]:
# Identifica valores ausentes e conta quantos existem em cada coluna
# Não verifica se os números preenchidos estão corretos
xp.isna().sum()

Price
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [21]:
# Mostra as cinco últimas linhas para observar datas, preços e volumes
xp['Close'].tail()

Date
2026-10-22    29.350
2026-10-23    30.410
2026-10-26    15.705
2026-10-27    15.960
2026-10-28    15.610
Name: Close, dtype: float64

In [24]:
# Recalcula as variações com os fechamentos que estão agora na variável xp
variacao_diaria = xp["Close"].pct_change() * 100

# Mostra as cinco últimas variações para conferir o resultado
variacao_diaria.tail()

Date
2026-10-22    -3.517422
2026-10-23     3.611582
2026-10-26   -48.355804
2026-10-27     1.623687
2026-10-28    -2.192985
Name: Close, dtype: float64

In [23]:
# Calcula a variação percentual entre os dois fechamentos informados
((15.870 / 15.960) - 1) * 100

-0.5639097744360999

In [25]:
# Cria uma tabela para comparar os fechamentos com a variação recalculada
conferencia = pd.DataFrame({
    "Fechamento": xp["Close"],
    "Variacao_%": xp["Close"].pct_change() * 100
})

# Mostra os cinco últimos registros da conferência
conferencia.tail()

            Fechamento  Variacao_%
Date
2026-10-22      29.350   -3.517422
2026-10-23      30.410    3.611582
2026-10-26      15.705  -48.355804
2026-10-27      15.960    1.623687
2026-10-28      15.610   -2.192985

In [26]:
# Mostra os registros do período escolhido, incluindo as duas datas
xp.loc["2026-10-23":"2026-10-27"]

Price        Close       High        Low    Open     Volume
Date
2026-10-23  30.410  30.639999  28.889999  29.500   12303900
2026-10-26  15.705  16.160000  13.780000  14.545  133089000
2026-10-27  15.960  16.639999  15.810000  16.010   41115200

### Validação do registro de 26/10/2026

- Identificamos uma variação de aproximadamente -48,36% no fechamento.
- Conferimos o registro no histórico da Nasdaq.
- Fechamento, abertura, máxima, mínima e volume coincidiram com a base.
- Decisão: manter o registro nesta etapa.
- A causa da mudança ainda precisa ser investigada.

In [27]:
# Identifica datas repetidas no índice e conta as repetições após a primeira ocorrência
xp.index.duplicated().sum()

np.int64(0)

In [28]:
# Verifica se as datas do índice estão em ordem crescente
xp.index.is_monotonic_increasing

True

In [31]:
# Mostra o tipo de dado armazenado em cada coluna
xp.dtypes

Price
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

In [32]:
# Seleciona apenas as quatro colunas de preços
precos = xp[["Open", "High", "Low", "Close"]]

# Conta quantos preços são menores ou iguais a zero em cada coluna
(precos <= 0).sum()

Price
Open     0
High     0
Low      0
Close    0
dtype: int64

In [33]:
# Conta os registros em que a máxima é menor que a mínima
(xp["High"] < xp["Low"]).sum()

np.int64(0)

In [34]:
# Identifica fechamentos abaixo da mínima ou acima da máxima
fechamento_fora = (xp["Close"] < xp["Low"]) | (xp["Close"] > xp["High"])

# Conta quantos registros apresentam essa inconsistência
fechamento_fora.sum()

np.int64(0)

In [35]:
# Identifica aberturas abaixo da mínima ou acima da máxima
abertura_fora = (xp["Open"] < xp["Low"]) | (xp["Open"] > xp["High"])

# Conta quantos registros apresentam essa inconsistência
abertura_fora.sum()

np.int64(0)

In [36]:
# Conta os registros em que o volume negociado é negativo
(xp["Volume"] < 0).sum()

np.int64(0)

In [37]:
# Conta os registros em que o volume negociado é igual a zero
(xp["Volume"] == 0).sum()

np.int64(0)

In [38]:
# Mostra a primeira e a última data presentes na base
xp.index.min(), xp.index.max()

(Timestamp('2019-12-11 00:00:00'), Timestamp('2026-10-28 00:00:00'))

In [39]:
# Cria uma cópia com os registros anteriores a 28/10/2026
xp_fechado = xp.loc[xp.index < "2026-10-28"].copy()

# Mostra as últimas cinco linhas para conferir o corte
xp_fechado.tail()

Price        Close       High        Low    Open     Volume
Date
2026-10-21  30.420  31.430000  30.290001  31.340   11833900
2026-10-22  29.350  30.389999  28.770000  29.900   13522300
2026-10-23  30.410  30.639999  28.889999  29.500   12303900
2026-10-26  15.705  16.160000  13.780000  14.545  133089000
2026-10-27  15.960  16.639999  15.810000  16.010   41115200

### Tratamento do pregão em andamento

- Data da conferência: 28/10/2026, às 12h16, horário de Brasília.
- O pregão ainda estava em andamento; os dados do dia poderiam mudar.
- Criamos a tabela xp_fechado somente com datas anteriores a 28/10/2026.
- A tabela original xp foi preservada.
- As próximas análises usarão xp_fechado.

In [40]:
# Mostra a quantidade de linhas e colunas da base com pregões encerrados
xp_fechado.shape

(1728, 5)

In [41]:
# Importa a ferramenta Path para trabalhar com caminhos de arquivos e pastas
from pathlib import Path

# Mostra a pasta de trabalho atual
Path.cwd()

WindowsPath('c:/Users/55119/Desktop/Projeto xp/analise-xp-inc/notebooks')

In [42]:
# Monta o caminho: sobe uma pasta e entra em data
pasta_dados = Path.cwd().parent / "data"

# Verifica se esse caminho corresponde a uma pasta existente
pasta_dados.is_dir()

True

In [44]:
# Define o nome e o caminho do arquivo CSV
arquivo_csv = pasta_dados / "xp_historico_fechado.csv"

# Salva a tabela, incluindo as datas que estão no índice
xp_fechado.to_csv(arquivo_csv, index=True)

# Mostra onde o arquivo foi salvo
arquivo_csv

WindowsPath('c:/Users/55119/Desktop/Projeto xp/analise-xp-inc/data/xp_historico_fechado.csv')

In [45]:
# Verifica se o arquivo CSV existe no caminho indicado
arquivo_csv.is_file()

True

In [46]:
# Lê o CSV e usa a coluna Date como índice
# Converte as datas de texto para o tipo de data do pandas
xp_conferencia = pd.read_csv(
    arquivo_csv,
    index_col="Date",
    parse_dates=True
)

# Mostra a quantidade de linhas e colunas do arquivo lido
xp_conferencia.shape

(1728, 5)

In [47]:
# Compara a tabela original com a tabela lida do CSV
# Aceita diferenças numéricas muito pequenas causadas pela gravação e leitura
pd.testing.assert_frame_equal(
    xp_fechado,
    xp_conferencia,
    check_names=False,
    check_freq=False,
    rtol=1e-9,
    atol=1e-9
)

### Salvamento e conferência da base

- Arquivo: data/xp_historico_fechado.csv.
- Base salva: 1.728 linhas e 5 colunas, com as datas no índice.
- Período: 11/12/2019 a 27/10/2026.
- O CSV foi reaberto e comparado com xp_fechado.
- A comparação passou dentro da tolerância numérica definida.